### PR TITLE
Update: Added readme

### PR DESCRIPTION
**Pull request by leoTiez**
Added description about the pre requirements and the data

### CODE REVIEW

**Review by adrianc-a — CHANGES_REQUESTED** [review]
Let's add a requirements.txt I think it will make it easier. Also, why are we using python2.7 not 3?

**Comment by leoTiez** [comment]
I agree, generally good practice, but thought it might be an over kill for just tensorflow and numpy which we all have already installed. Nevertheless, good point and I added it!

I prefer in general python 2.7 over python 3 because they have removed some very handy iteration tools in python 3 like enumerating a zip() iterable, etc.

**Comment by adrianc-a** [comment]
Yeah for two it's a bit overkill, but with the others you had it made more sense. Though I guess those have gone now (cPickle)?

**Review by adrianc-a — APPROVED** [review]

**Comment by leoTiez** [comment]
Ah yea, forgot to remove it from the readme. I checked it, it is a standard library of python so no need to install that. I have removed it now.

**Pull request merged**
